# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jennings Makes Stuff
author: Jennings Hanna
email: jenningshanna@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An archive of my writings and musings.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shiplog.jenningshanna.com/" # the base hostname & protocol for your site
twitter_username: jenningshanna
github_username:  jenningshanna
dribble_username:  jenningshanna
medium_username:  jenningshanna

# Build settings
markdown: kramdown
